### ISSUE TITLE
 iter_start_contrastive = 300000？

### ISSUE THREAD

**Issue by kaigelee** [qianyuzqy/RCCR#1]
想问下代码中 iter_start_contrastive 设置为 300000
但是总训练轮数只有250000，
所以是永远不启动contrastive吗？

**Comment by qianyuzqy** [comment]
@kaigelee 您好，感谢关注。我们这个config中是为了对比DACS才把iter_start_contrastive 设置为了一个很大的数，后来上传的config没有把这里改过来。您可以把iter_start_contrastive设置为0从头开始训练，或者根据您使用的数据集重新调整合适的参数。

多谢！
